spring:
  mail:
    host: smtp.163.com
    username: nvj335537@163.com
    password: EDEUKSDOTYFZSOWD
  rabbitmq:
    addresses: 192.168.127.136
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: abcdefg
      expire: 7
  datasource:
    url: jdbc:mysql://192.168.127.136:3306/monitor
    username: root
    password: 5Mdmhf5t6wPDYKcQ
    driver-class-name: com.mysql.cj.jdbc.Driver
  influx:
    url: http://192.168.127.136:8086
    user: influxdb_walnker
    password: influxdb_123456
  data:
    redis:
      host: 192.168.127.136
      port: 6379
      password: redis_MANDKd
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

